[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_18"]

[phases.install]
cmds = [
    "cd supportops-tracker && composer install --no-dev --optimize-autoloader --no-scripts",
    "cd supportops-tracker && npm install"
]

[phases.build]
cmds = [
    "cd supportops-tracker && npm run build"
]
